import { CityModel } from "../../Model/CityModel.js"

export const SeedCity = async () => {
    await CityModel.deleteMany({})
    await CityModel.create([
        { cityName: "Mid Glamorgan" },
        { cityName: "Aberdeenshire" },
        { cityName: "Gwynedd" },
        { cityName: "Gwent" },
        { cityName: "Clwyd" },
        { cityName: "Gwent" },
        { cityName: "Dyfed" },
        { cityName: "Oxfordshire" },
        { cityName: "Lancashire" },
        { cityName: "Lanarkshire" },
        { cityName: "Warwickshire" },
        { cityName: "Suffolk" },
        { cityName: "Cheshire" },
        { cityName: "Hampshire" },
        { cityName: "Derbyshire" },
        { cityName: "Ross-shire" },
        { cityName: "Northumberland" },
        { cityName: "Hampshire" },
        { cityName: "Cumbria" },
        { cityName: "Hampshire" },
        { cityName: "Cheshire" },
        { cityName: "Cumbria" },
        { cityName: "Buckinghamshire" },
        { cityName: "Wiltshire" },
        { cityName: "Carmarthenshire" },
        { cityName: "Hampshire" },
        { cityName: "Fife" },
        { cityName: "Co Antrim" },
        { cityName: "Cumbria" },
        { cityName: "Angus" },
        { cityName: "Ayrshire" },
        { cityName: "Co Armagh" },
        { cityName: "Gwynedd" },
        { cityName: "West Sussex" },
        { cityName: "Berkshire" },
        { cityName: "Derbyshire" },
        { cityName: "Devon" },
        { cityName: "Middlesex" },
        { cityName: "Northumberland" },
        { cityName: "Surrey" },
        { cityName: "Greater Manchester" },
        { cityName: "Norfolk" },
        { cityName: "Inverness-shire" },
        { cityName: "Devon" },
        { cityName: "Buckinghamshire" },
        { cityName: "Ayrshire" },
        { cityName: "Gwynedd" },
        { cityName: "Hertfordshire" },
        { cityName: "Argyll" },
        { cityName: "Co Antrim" },
        { cityName: "Co Antrim" },
        { cityName: "Co Antrim" },
        { cityName: "Co Antrim" },
        { cityName: "Northumberland" },
        { cityName: "Devon" },
        { cityName: "Co Down" },
        { cityName: "Oxfordshire" },
        { cityName: "Kincardineshire" },
        { cityName: "Aberdeenshire" },
        { cityName: "Gwynedd" },
        { cityName: "Surrey" },
        { cityName: "Essex" },
        { cityName: "Gwynedd" },
        { cityName: "Co Durham" },
        { cityName: "Hertfordshire" },
        { cityName: "South Yorkshire" },
        { cityName: "Devon" },
        { cityName: "South Glamorgan" },
        { cityName: "Cumbria" },
        { cityName: "South Humberside" },
        { cityName: "Essex" },
        { cityName: "Hampshire" },
        { cityName: "Avon" },
        { cityName: "West Lothian" },
        { cityName: "East Sussex" },
        { cityName: "Gwynedd" },
        { cityName: "Suffolk" },
        { cityName: "Kent" },
        { cityName: "North Yorkshire" },
        { cityName: "Bedfordshire" },
        { cityName: "Belfast" },
        { cityName: "Kent" },
        { cityName: "Essex" },
        { cityName: "Hertfordshire" },
        { cityName: "Northumberland" },
        { cityName: "Conwy" },
        { cityName: "North Humberside" },
        { cityName: "Worcestershire" },
        { cityName: "East Sussex" },
        { cityName: "Oxfordshire" },
        { cityName: "Devon" },
        { cityName: "Lanarkshire" },
        { cityName: "Bedfordshire" },
        { cityName: "Essex" },
        { cityName: "West Sussex" },
        { cityName: "West Yorkshire" },
        { cityName: "Merseyside" },
        { cityName: "West Midlands" },
        { cityName: "Co Durham" },
        { cityName: "Shropshire" },
        { cityName: "Hertfordshire" },
        { cityName: "Hampshire" },
        { cityName: "Lancashire" },
        { cityName: "Lancashire" },
        { cityName: "Gwynedd" },
        { cityName: "Perthshire" },
        { cityName: "Dorset" },
        { cityName: "Tyne and Wear" },
        { cityName: "Cornwall" },
        { cityName: "West Sussex" },
        { cityName: "Tyne and Wear" },
        { cityName: "Lancashire" },
        { cityName: "Midlothian" },
        { cityName: "Merseyside" },
        { cityName: "Hampshire" },
        { cityName: "Hertfordshire" },
        { cityName: "Lincolnshire" },
        { cityName: "West Lothian" },
        { cityName: "Lincolnshire" },
        { cityName: "Dorset" },
        { cityName: "Northamptonshire" },
        { cityName: "Berkshire" },
        { cityName: "West Yorkshire" },
        { cityName: "Essex" },
        { cityName: "Cumbria" },
        { cityName: "Devon" },
        { cityName: "Powys" },
        { cityName: "Middlesex" },
        { cityName: "Essex" },
        { cityName: "Mid Glamorgan" },
        { cityName: "Shropshire" },
        { cityName: "Somerset" },
        { cityName: "North Humberside" },
        { cityName: "Dorset" },
        { cityName: "Lincolnshire" },
        { cityName: "West Yorkshire" },
        { cityName: "East Sussex" },
        { cityName: "Avon" },
        { cityName: "Devon" },
        { cityName: "Isle of Skye" },
        { cityName: "Kent" },
        { cityName: "Hereford and Worcester" },
        { cityName: "Hampshire" },
        { cityName: "Isle of Arran" },
        { cityName: "Kent" },
        { cityName: "Hereford and Worcester" },
        { cityName: "Norfolk" },
        { cityName: "West Lothian" },
        { cityName: "Devon" },
        { cityName: "Essex" },
        { cityName: "Banffshire" },
        { cityName: "Buckinghamshire" },
        { cityName: "Cornwall" },
        { cityName: "Devon" },
        { cityName: "Powys" },
        { cityName: "Isle of Mull" },
        { cityName: "Suffolk" },
        { cityName: "West Sussex" },
        { cityName: "Somerset" },
        { cityName: "Lancashire" },
        { cityName: "Staffordshire" },
        { cityName: "Lancashire" },
        { cityName: "Suffolk" },
        { cityName: "Co Antrim" },
        { cityName: "Derbyshire" },
        { cityName: "Gwynedd" },
        { cityName: "Mid Glamorgan" },
        { cityName: "Wiltshire" },
        { cityName: "Surrey" },
        { cityName: "Cambridgeshire" },
        { cityName: "Cornwall" },
        { cityName: "Argyll" },
        { cityName: "Staffordshire" },
        { cityName: "Kent" },
        { cityName: "South Glamorgan" },
        { cityName: "Dyfed" },
        { cityName: "Cumbria" },
        { cityName: "Isle of Lewis" },
        { cityName: "Lanarkshire" },
        { cityName: "Dyfed" },
        { cityName: "Lancashire" },
        { cityName: "Co Antrim" },
        { cityName: "Surrey" },
        { cityName: "Kirkcudbrightshire" },
        { cityName: "Co Tyrone" },
        { cityName: "Isle of Man" },
        { cityName: "Co Down" },
        { cityName: "Surrey" },
        { cityName: "Gwynedd" },
        { cityName: "Gwynedd" },
        { cityName: "Dorset" },
        { cityName: "Somerset" },
        { cityName: "Kent" },
        { cityName: "Cambridgeshire" },
        { cityName: "Cheshire" },
        { cityName: "Surrey" },
        { cityName: "Somerset" },
        { cityName: "Essex" },
        { cityName: "Gloucestershire" },
        { cityName: "Gwent" },
        { cityName: "Surrey" },
        { cityName: "Buckinghamshire" },
        { cityName: "Cheshire" },
        { cityName: "Co Durham" },
        { cityName: "Derbyshire" },
        { cityName: "West Sussex" },
        { cityName: "Wiltshire" },
        { cityName: "Oxfordshire" },
        { cityName: "Gloucestershire" },
        { cityName: "Lancashire" },
        { cityName: "Dorset" },
        { cityName: "Shropshire" },
        { cityName: "Gloucestershne" },
        { cityName: "Gloucestershire" },
        { cityName: "Essex" },
        { cityName: "South Humberside" },
        { cityName: "Avon" },
        { cityName: "Lancashire" },
        { cityName: "Co Tyrone" },
        { cityName: "Northamptonshire" },
        { cityName: "Leicestershire" },
        { cityName: "Lanarkshire" },
        { cityName: "Surrey" },
        { cityName: "Cumbria" },
        { cityName: "Essex" },
        { cityName: "Warwickshire" },
        { cityName: "Co Londonderry" },
        { cityName: "Clwyd" },
        { cityName: "Cheshire" },
        { cityName: "Cumbria" },
        { cityName: "Co Durham" },
        { cityName: "Gwynedd" },
        { cityName: "Co Tyrone" },
        { cityName: "Lancashire" },
        { cityName: "Northumberland" },
        { cityName: "Northamptonshire" },
        { cityName: "Clwyd" },
        { cityName: "Surrey" },
        { cityName: "West Midlands" },
        { cityName: "Co Armagh" },
        { cityName: "Northumberland" },
        { cityName: "Kent" },
        { cityName: "Surrey" },
        { cityName: "Shropshire" },
        { cityName: "West Sussex" },
        { cityName: "Devon" },
        { cityName: "Cheshire" },
        { cityName: "Perthshire" },
        { cityName: "Norfolk" },
        { cityName: "East Sussex" },
        { cityName: "Inverness-shire" },
        { cityName: "Surrey" },
        { cityName: "Co Antrim" },
        { cityName: "Devon" },
        { cityName: "East Ayrshire" },
        { cityName: "Fife" },
        { cityName: "Gwent" },
        { cityName: "Essex" },
        { cityName: "Kirkcudbrightshire" },
        { cityName: "Argyll" },
        { cityName: "Ayrshire" },
        { cityName: "Co Durham" },
        { cityName: "Kent" },
        { cityName: "Ayrshire" },
        { cityName: "Northamptonshire" },
        { cityName: "Kent" },
        { cityName: "Clwyd" },
        { cityName: "Derbyshire" },
        { cityName: "Norfolk" },
        { cityName: "Wiltshire" },
        { cityName: "West Yorkshire" },
        { cityName: "Oxfordshire" },
        { cityName: "South Glamorgan" },
        { cityName: "Ross-shire" },
        { cityName: "Norfolk" },
        { cityName: "Gwynedd" },
        { cityName: "South Yorkshire" },
        { cityName: "Dorset" },
        { cityName: "Surrey" },
        { cityName: "Sutherland" },
        { cityName: "Isle of Man" },
        { cityName: "Kent" },
        { cityName: "Norfolk" },
        { cityName: "Co Down" },
        { cityName: "North Humberside" },
        { cityName: "Hereford and Worcester" },
        { cityName: "Co Down" },
        { cityName: "West Midlands" },
        { cityName: "Somerset" },
        { cityName: "Dunbartonshire" },
        { cityName: "Dumfriesshire" },
        { cityName: "East Lothian" },
        { cityName: "Perthshire" },
        { cityName: "Angus" },
        { cityName: "Fife" },
        { cityName: "Co Tyrone" },
        { cityName: "Perthshire" },
        { cityName: "Essex" },
        { cityName: "Belfast" },
        { cityName: "Argyll" },
        { cityName: "Berwickshire" },
        { cityName: "Bedfordshire" },
        { cityName: "Co Durham" },
        { cityName: "Gloucestershire" },
        { cityName: "North Yorkshire" },
        { cityName: "West Sussex" },
        { cityName: "South Lanarkshire" },
        { cityName: "Surrey" },
        { cityName: "East Sussex" },
        { cityName: "Hampshire" },
        { cityName: "Kent" },
        { cityName: "Gwent" },
        { cityName: "Kent" },
        { cityName: "Middlesex" },
        { cityName: "Edinburgh" },
        { cityName: "Surrey" },
        { cityName: "Morayshire" },
        { cityName: "Cheshire" },
        { cityName: "Aberdeenshire" },
        { cityName: "Cambridgeshire" },
        { cityName: "Hampshire" },
        { cityName: "Middlesex" },
        { cityName: "Co Fermanagh" },
        { cityName: "Essex" },
        { cityName: "Surrey" },
        { cityName: "Kent" },
        { cityName: "Surrey" },
        { cityName: "Worcestershire" },
        { cityName: "Devon" },
        { cityName: "Devon" },
        { cityName: "Norfolk" },
        { cityName: "Stirlingshire" },
        { cityName: "Cornwall" },
        { cityName: "Hampshire" },
        { cityName: "Oxfordshire" },
        { cityName: "Hampshire" },
        { cityName: "Surrey" },
        { cityName: "Suffolk" },
        { cityName: "Dyfed" },
        { cityName: "Co Tyrone" },
        { cityName: "Hampshire" },
        { cityName: "Lancashire" },
        { cityName: "Clwyd" },
        { cityName: "Kent" },
        { cityName: "Angus" },
        { cityName: "Inverness-shire" },
        { cityName: "Ross-shire" },
        { cityName: "Cornwall" },
        { cityName: "Aberdeenshire" },
        { cityName: "Isle of Wight" },
        { cityName: "Essex" },
        { cityName: "Somerset" },
        { cityName: "Lincolnshire" },
        { cityName: "Ross-shire" },
        { cityName: "Selkirkshire" },
        { cityName: "Lancashire" },
        { cityName: "Tyne and Wear" },
        { cityName: "Buckinghamshire" },
        { cityName: "Kent" },
        { cityName: "South Ayrshire" },
        { cityName: "Rotherham" },
        { cityName: "Glasgow" },
        { cityName: "Somerset" },
        { cityName: "Fife" },
        { cityName: "Derbyshire" },
        { cityName: "Gloucestershire" },
        { cityName: "Surrey" },
        { cityName: "Surrey" },
        { cityName: "East Riding of Yorkshire" },
        { cityName: "Cumbria" },
        { cityName: "Hampshire" },
        { cityName: "Cumbria" },
        { cityName: "Midlothian" },
        { cityName: "Lincolnshire" },
        { cityName: "Kent" },
        { cityName: "Essex" },
        { cityName: "Essex" },
        { cityName: "Buckinghamshire" },
        { cityName: "Norfolk" },
        { cityName: "Middlesex" },
        { cityName: "Renfrewshire" },
        { cityName: "Dumfriesshire" },
        { cityName: "South Humberside" },
        { cityName: "Channel Islands" },
        { cityName: "Surrey" },
        { cityName: "North Yorkshire" },
        { cityName: "West Yorkshire" },
        { cityName: "East Lothian" },
        { cityName: "Lanark shire" },
        { cityName: "East Lothian" },
        { cityName: "East Sussex" },
        { cityName: "West Midlands" },
        { cityName: "West Yorkshire" },
        { cityName: "Essex" },
        { cityName: "Northumberland" },
        { cityName: "Middlesex" },
        { cityName: "Essex" },
        { cityName: "Hertfordshire" },
        { cityName: "North Yorkshire" },
        { cityName: "Middlesex" },
        { cityName: "Cleveland" },
        { cityName: "Essex" },
        { cityName: "Surrey" },
        { cityName: "West Sussex" },
        { cityName: "East Sussex" },
        { cityName: "Hertfordshire" },
        { cityName: "Derbyshire" },
        { cityName: "Hampshire" },
        { cityName: "Pembrokeshire" },
        { cityName: "Suffolk" },
        { cityName: "Roxburghshire" },
        { cityName: "Cumbria" },
        { cityName: "Powys" },
        { cityName: "Middlesex" },
        { cityName: "Hampshire" },
        { cityName: "West Sussex" },
        { cityName: "Derbyshire" },
        { cityName: "East Sussex" },
        { cityName: "Dunbartonshire" },
        { cityName: "North Yorkshire" },
        { cityName: "Cornwall" },
        { cityName: "Hertfordshire" },
        { cityName: "West Sussex" },
        { cityName: "Oxfordshire" },
        { cityName: "Hereford and Worcester" },
        { cityName: "Kent" },
        { cityName: "Hertfordshire" },
        { cityName: "North Humberside" },
        { cityName: "Northumberland" },
        { cityName: "Lancashire" },
        { cityName: "Buckinghamshire" },
        { cityName: "Somerset" },
        { cityName: "Co Down" },
        { cityName: "Leicestershire" },
        { cityName: "Surrey" },
        { cityName: "Hertfordshire" },
        { cityName: "Essex" },
        { cityName: "Hertfordshire" },
        { cityName: "Lincolnshire" },
        { cityName: "Cheshire" },
        { cityName: "Devon" },
        { cityName: "Norfolk" },
        { cityName: "Gwynedd" },
        { cityName: "Co Down" },
        { cityName: "Lincolnshire" },
        { cityName: "Devon" },
        { cityName: "Hampshire" },
        { cityName: "Surrey" },
        { cityName: "Lancashire" },
        { cityName: "Essex" },
        { cityName: "East Riding of Yorkshire" },
        { cityName: "West Sussex" },
        { cityName: "Tyne and Wear" },
        { cityName: "Middlesex" },
        { cityName: "East Sussex" },
        { cityName: "West Yorkshire" },
        { cityName: "North Humberside" },
        { cityName: "Berkshire" },
        { cityName: "Norfolk" },
        { cityName: "Cambridgeshire" },
        { cityName: "Aberdeenshire" },
        { cityName: "Cheshire" },
        { cityName: "Kent" },
        { cityName: "Essex" },
        { cityName: "Devon" },
        { cityName: "Derbyshire" },
        { cityName: "West Yorkshire" },
        { cityName: "South Humberside" },
        { cityName: "Essex" },
        { cityName: "Aberdeenshire" },
        { cityName: "Argyll" },
        { cityName: "Inverness-shire" },
        { cityName: "Aberdeenshire" },
        { cityName: "Isle of Iona" },
        { cityName: "Staffordshire" },
        { cityName: "Suffolk" },
        { cityName: "Shropshire" },
        { cityName: "Isle of Wight" },
        { cityName: "Middlesex" },
        { cityName: "Channel Islands" },
        { cityName: "Renfrewshire" },
        { cityName: "West Yorkshire" },
        { cityName: "Roxburghshire" },
        { cityName: "Cumbria" },
        { cityName: "Warwickshire" },
        { cityName: "Cumbria" },
        { cityName: "Northamptonshire" },
        { cityName: "Hereford and Worcester" },
        { cityName: "Ayrshire" },
        { cityName: "Perthshire" },
        { cityName: "Lincolnshire" },
        { cityName: "Renfrewshire" },
        { cityName: "Ayrshire" },
        { cityName: "Norfolk" },
        { cityName: "Hertfordshire" },
        { cityName: "Devon" },
        { cityName: "Surrey" },
        { cityName: "West Midlands" },
        { cityName: "Herefordshire" },
        { cityName: "Inverness-shire" },
        { cityName: "Cumbria" },
        { cityName: "Fife" },
        { cityName: "Northumberland" },
        { cityName: "Angus" },
        { cityName: "Powys" },
        { cityName: "Cheshire" },
        { cityName: "Ross-shire" },
        { cityName: "Isle of Skye" },
        { cityName: "Essex" },
        { cityName: "Sutherland" },
        { cityName: "Ceredigion" },
        { cityName: "Lanarkshire" },
        { cityName: "Lancashire" },
        { cityName: "West Sussex" },
        { cityName: "Warwickshire" },
        { cityName: "Stirlingshire" },
        { cityName: "Caithness" },
        { cityName: "Cornwall" },
        { cityName: "Warwickshire" },
        { cityName: "Surrey" },
        { cityName: "Hereford and Worcester" },
        { cityName: "West Yorkshire" },
        { cityName: "Leicestershire" },
        { cityName: "Lancashire" },
        { cityName: "Essex" },
        { cityName: "Bedfordshire" },
        { cityName: "Suffolk" },
        { cityName: "Hereford and Worcester" },
        { cityName: "Isle of Shetland" },
        { cityName: "Hertfordshire" },
        { cityName: "East Sussex" },
        { cityName: "North Yorkshire" },
        { cityName: "Lancashire" },
        { cityName: "Staffordshire" },
        { cityName: "Surrey" },
        { cityName: "Co Londonderry" },
        { cityName: "Lincolnshire" },
        { cityName: "Surrey" },
        { cityName: "Hampshire" },
        { cityName: "Co Antrim" },
        { cityName: "Cornwall" },
        { cityName: "Hampshire" },
        { cityName: "Lancashire" },
        { cityName: "West Sussex" },
        { cityName: "Merseyside" },
        { cityName: "West Lothian" },
        { cityName: "Ceredigion" },
        { cityName: "Gwynedd" },
        { cityName: "Carmarthenshire" },
        { cityName: "Carmarthenshire" },
        { cityName: "Powys" },
        { cityName: "Gwynedd" },
        { cityName: "Dyfed" },
        { cityName: "Dyfed" },
        { cityName: "Clwyd" },
        { cityName: "Powys" },
        { cityName: "Ceredigion" },
        { cityName: "Gwynedd" },
        { cityName: "South Glamorgan" },
        { cityName: "Dyfed" },
        { cityName: "Powys" },
        { cityName: "Midlothian" },
        { cityName: "Isle of Uist" },
        { cityName: "Ross-shire" },
        { cityName: "Argyll" },
        { cityName: "Renfrewshire" },
        { cityName: "Dumfriesshire" },
        { cityName: "London" },
        { cityName: "Co Londonderry" },
        { cityName: "Leicestershire" },
        { cityName: "Essex" },
        { cityName: "Lincolnshire" },
        { cityName: "Suffolk" },
        { cityName: "Shropshire" },
        { cityName: "Co Antrim" },
        { cityName: "Bedfordshire" },
        { cityName: "Leicestershire" },
        { cityName: "Gloucestershire" },
        { cityName: "Hampshire" },
        { cityName: "Hampshire" },
        { cityName: "Devon" },
        { cityName: "Lancashire" },
        { cityName: "Cheshire" },
        { cityName: "Powys" },
        { cityName: "Cambridgeshire" },
        { cityName: "Mid Glamorgan" },
        { cityName: "Co Londonderry" },
        { cityName: "Berkshire" },
        { cityName: "Kent" },
        { cityName: "Essex" },
        { cityName: "Wiltshire" },
        { cityName: "Cheshire" },
        { cityName: "North Yorkshire" },
        { cityName: "Hereford and Worcester" },
        { cityName: "Greater Manchester" },
        { cityName: "Nottinghamshire" },
        { cityName: "Cambridgeshire" },
        { cityName: "Kent" },
        { cityName: "Shropshire" },
        { cityName: "Leicestershire" },
        { cityName: "Lincolnshire" },
        { cityName: "East Riding of Yorkshire" },
        { cityName: "Wiltshire" },
        { cityName: "Buckinghamshire" },
        { cityName: "Lincolnshire" },
        { cityName: "Cumbria" },
        { cityName: "Derbyshire" },
        { cityName: "Aberdeenshire" },
        { cityName: "Kent" },
        { cityName: "Powys" },
        { cityName: "Wiltshire" },
        { cityName: "Leicestershire" },
        { cityName: "Wiltshire" },
        { cityName: "West Midlands" },
        { cityName: "Mid Glamorgan" },
        { cityName: "South Yorkshire" },
        { cityName: "Cleveland" },
        { cityName: "Cheshire" },
        { cityName: "West Sussex" },
        { cityName: "Suffolk" },
        { cityName: "Pembrokeshire" },
        { cityName: "Buckinghamshire" },
        { cityName: "Somerset" },
        { cityName: "West Yorkshire" },
        { cityName: "Surrey" },
        { cityName: "Gloucestershire" },
        { cityName: "Clwyd" },
        { cityName: "Gwent" },
        { cityName: "Powys" },
        { cityName: "Angus" },
        { cityName: "Surrey" },
        { cityName: "Lancashire" },
        { cityName: "Devon" },
        { cityName: "Northumberiand" },
        { cityName: "East Ayrshire" },
        { cityName: "Lanarkshire" },
        { cityName: "Midlothian" },
        { cityName: "Avon" },
        { cityName: "Inverness-shire" },
        { cityName: "Cheshire" },
        { cityName: "Pembrokeshire" },
        { cityName: "Neath Port Talbot" },
        { cityName: "Gwynedd" },
        { cityName: "Lancashire" },
        { cityName: "Inverness-shire" },
        { cityName: "Surrey" },
        { cityName: "Derbyshire" },
        { cityName: "Nottinghamshire" },
        { cityName: "Berkshire" },
        { cityName: "Staffordshire" },
        { cityName: "Dyfed" },
        { cityName: "Tyne and Wear" },
        { cityName: "Roxburghshire" },
        { cityName: "Gloucestershire" },
        { cityName: "East Sussex" },
        { cityName: "Suffolk" },
        { cityName: "Shropshire" },
        { cityName: "Buckinghamshire" },
        { cityName: "Cornwall" },
        { cityName: "Devon" },
        { cityName: "Powys" },
        { cityName: "Merseyside" },
        { cityName: "Co Antrim" },
        { cityName: "Co Down" },
        { cityName: "East Lothian" },
        { cityName: "Tyne and Wear" },
        { cityName: "Norfolk" },
        { cityName: "North Yorkshire" },
        { cityName: "Northamptonshire" },
        { cityName: "Cheshire" },
        { cityName: "Middlesex" },
        { cityName: "Norfolk" },
        { cityName: "Nottinghamshire" },
        { cityName: "Nottinghamshire" },
        { cityName: "Warwickshire" },
        { cityName: "Leicestershire" },
        { cityName: "Argyll" },
        { cityName: "Devon" },
        { cityName: "Lancashire" },
        { cityName: "Co Tyrone" },
        { cityName: "Essex" },
        { cityName: "Lancashire" },
        { cityName: "Kent" },
        { cityName: "West Yorkshire" },
        { cityName: "Shropshire" },
        { cityName: "West Yorkshire" },
        { cityName: "Oxfordshire" },
        { cityName: "Surrey" },
        { cityName: "Devon" },
        { cityName: "Renfrewshire" },
        { cityName: "Suffolk" },
        { cityName: "Cornwall" },
        { cityName: "Dyfed" },
        { cityName: "South Glamorgan" },
        { cityName: "Herefordshire" },
        { cityName: "Midlothian" },
        { cityName: "Gwynedd" },
        { cityName: "Gwynedd" },
        { cityName: "Cumbria" },
        { cityName: "Cornwall" },
        { cityName: "Cornwall" },
        { cityName: "Hereford and Worcester" },
        { cityName: "Perthshire" },
        { cityName: "Cambridgeshire" },
        { cityName: "Aberdeenshire" },
        { cityName: "Hampshire" },
        { cityName: "West Sussex" },
        { cityName: "East Sussex" },
        { cityName: "Wiltshire" },
        { cityName: "North Yorkshire" },
        { cityName: "Middlesex" },
        { cityName: "Perthshire" },
        { cityName: "Devon" },
        { cityName: "East Riding of Yorkshire" },
        { cityName: "West Yorkshire" },
        { cityName: "Mid Glamorgan" },
        { cityName: "Torfaen" },
        { cityName: "Mid Glamorgan" },
        { cityName: "Dorset" },
        { cityName: "Cumbria" },
        { cityName: "Cornwall" },
        { cityName: "West Glamorgan" },
        { cityName: "Mid Glamorgan" },
        { cityName: "Gwynedd" },
        { cityName: "Isle of Skye" },
        { cityName: "Co Antrim" },
        { cityName: "Hampshire" },
        { cityName: "Hertfordshire" },
        { cityName: "Lancashire" },
        { cityName: "Merseyside" },
        { cityName: "Clwyd" },
        { cityName: "Lancashire" },
        { cityName: "Ayrshire" },
        { cityName: "Buckinghamshire" },
        { cityName: "Northumberland" },
        { cityName: "West Sussex" },
        { cityName: "Surrey" },
        { cityName: "Gwynedd" },
        { cityName: "&nbsp;" },
        { cityName: "Hertfordshire" },
        { cityName: "Isle of Man" },
        { cityName: "Kent" },
        { cityName: "Cumbria" },
        { cityName: "Essex" },
        { cityName: "Berkshire" },
        { cityName: "Cleveland" },
        { cityName: "Hereford and" },
        { cityName: "Surrey" },
        { cityName: "Cornwall" },
        { cityName: "Surrey" },
        { cityName: "Nottmghamshire" },
        { cityName: "Clwyd" },
        { cityName: "Surrey" },
        { cityName: "Hertfordshire" },
        { cityName: "Northumberland" },
        { cityName: "Hampshire" },
        { cityName: "Derbyshire" },
        { cityName: "North Yorkshire" },
        { cityName: "East Sussex" },
        { cityName: "Lancashire" },
        { cityName: "Kent" },
        { cityName: "Essex" },
        { cityName: "Hampshire" },
        { cityName: "Essex" },
        { cityName: "Hampshire" },
        { cityName: "Herefordshire" },
        { cityName: "Lancashire" },
        { cityName: "Northumberland" },
        { cityName: "South Yorkshire" },
        { cityName: "Isle ofBute" },
        { cityName: "Hertfordshire" },
        { cityName: "Warwickshire" },
        { cityName: "Staffordshire" },
        { cityName: "Middlesex" },
        { cityName: "Cheshire" },
        { cityName: "Northamptonshire" },
        { cityName: "Clwyd" },
        { cityName: "East Sussex" },
        { cityName: "Tyne and Wear" },
        { cityName: "Essex" },
        { cityName: "Lancashire" },
        { cityName: "Wiltshire" },
        { cityName: "Cornwall" },
        { cityName: "Cleveland" },
        { cityName: "Ayrshire" },
        { cityName: "Cheshire" },
        { cityName: "Berkshire" },
        { cityName: "Isle of Wight" },
        { cityName: "Kent" },
        { cityName: "Bedfordshire" },
        { cityName: "Dumfriesshire" },
        { cityName: "Hertfordshire" },
        { cityName: "Suffolk" },
        { cityName: "North Yorkshire" },
        { cityName: "Isle of Tiree" },
        { cityName: "South Humberside" },
        { cityName: "East Sussex" },
        { cityName: "Co Durham" },
        { cityName: "Northumberland" },
        { cityName: "Devon" },
        { cityName: "Cumbria" },
        { cityName: "Co Durham" },
        { cityName: "North Yorkshire" },
        { cityName: "Selkirkshire" },
        { cityName: "North Yorkshire" },
        { cityName: "Kent" },
        { cityName: "Wiltshire" },
        { cityName: "Cumbria" },
        { cityName: "Isle of Lewis" },
        { cityName: "South Yorkshire" },
        { cityName: "Middlesex" },
        { cityName: "Somerset" },
        { cityName: "Dorset" },
        { cityName: "Norfolk" },
        { cityName: "Isle of Shetland" },
        { cityName: "Shropshire" },
        { cityName: "West Yorkshire" },
        { cityName: "Shropshire" },
        { cityName: "Kent" },
        { cityName: "Devon" },
        { cityName: "Kent" },
        { cityName: "Lincolnshire" },
        { cityName: "Lancashire" },
        { cityName: "North Yorkshire" },
        { cityName: "Lincolnshire" },
        { cityName: "Berkshire" },
        { cityName: "West Midlands" },
        { cityName: "Surrey" },
        { cityName: "West Lothian" },
        { cityName: "Devon" },
        { cityName: "Somerset" },
        { cityName: "Merseyside" },
        { cityName: "Middlesex" },
        { cityName: "Warwickshire" },
        { cityName: "Hampshire" },
        { cityName: "Essex" },
        { cityName: "Essex" },
        { cityName: "Merseyside" },
        { cityName: "Hampshire" },
        { cityName: "Nottinghamshire" },
        { cityName: "North Yorkshire" },
        { cityName: "Lincolnshire" },
        { cityName: "Lincolnshire" },
        { cityName: "Hertfordshire" },
        { cityName: "Fife" },
        { cityName: "Clwyd" },
        { cityName: "Cornwall" },
        { cityName: "Carmarthenshire" },
        { cityName: "Merseyside" },
        { cityName: "Cornwall" },
        { cityName: "East Sussex" },
        { cityName: "Staffordshire" },
        { cityName: "Middlesex" },
        { cityName: "Lincolnshire" },
        { cityName: "Essex" },
        { cityName: "Middlesex" },
        { cityName: "Hertfordshire" },
        { cityName: "Stirlingshire" },
        { cityName: "Cheshire" },
        { cityName: "Northumberland" },
        { cityName: "Cleveland" },
        { cityName: "Staffordshire" },
        { cityName: "Staffordshire" },
        { cityName: "Kincardineshire" },
        { cityName: "Isle of Lewis" },
        { cityName: "West Midlands" },
        { cityName: "Hereford and Worcester" },
        { cityName: "Gloucestershire" },
        { cityName: "Suffolk" },
        { cityName: "Wigtownshire" },
        { cityName: "Warwickshire" },
        { cityName: "Ross-shire" },
        { cityName: "South Lanarkshire" },
        { cityName: "Ross-shire" },
        { cityName: "Somerset" },
        { cityName: "Gloucestershire" },
        { cityName: "Suffolk" },
        { cityName: "Middlesex" },
        { cityName: "Tyne and Wear" },
        { cityName: "Surrey" },
        { cityName: "Surrey" },
        { cityName: "West Midlands" },
        { cityName: "Nottinghamshire" },
        { cityName: "Norfolk" },
        { cityName: "Dorset" },
        { cityName: "Kent" },
        { cityName: "West Glamorgan" },
        { cityName: "Wiltshire" },
        { cityName: "Ross-shire" },
        { cityName: "Gwynedd" },
        { cityName: "Staffordshire" },
        { cityName: "Argyll" },
        { cityName: "Cheshire" },
        { cityName: "Somerset" },
        { cityName: "Devon" },
        { cityName: "Middlesex" },
        { cityName: "Devon" },
        { cityName: "Shropshire" },
        { cityName: "Somerset" },
        { cityName: "Somerset" },
        { cityName: "Dyfed" },
        { cityName: "Gloucestershire" },
        { cityName: "Oxfordshire" },
        { cityName: "Kent" },
        { cityName: "Berkshire" },
        { cityName: "Norfolk" },
        { cityName: "North Yorkshire" },
        { cityName: "Surrey" },
        { cityName: "Caithness" },
        { cityName: "Essex" },
        { cityName: "West Midlands" },
        { cityName: "Devon" },
        { cityName: "Kent" },
        { cityName: "Devon" },
        { cityName: "Devon" },
        { cityName: "Isle of Wight" },
        { cityName: "Northamptonshire" },
        { cityName: "East Lothian" },
        { cityName: "Gwent" },
        { cityName: "Hertfordshire" },
        { cityName: "Wiltshire" },
        { cityName: "Cornwall" },
        { cityName: "Kent" },
        { cityName: "Aberdeenshire" },
        { cityName: "Middlesex" },
        { cityName: "Gwynedd" },
        { cityName: "East Sussex" },
        { cityName: "Cumbria" },
        { cityName: "Devon" },
        { cityName: "Staffordshire" },
        { cityName: "Middlesex" },
        { cityName: "Isle ofWight" },
        { cityName: "Cornwall" },
        { cityName: "West Yorkshire" },
        { cityName: "Merseyside" },
        { cityName: "Oxfordshire" },
        { cityName: "Surrey" },
        { cityName: "West Midlands" },
        { cityName: "Norfolk" },
        { cityName: "Hertfordshire" },
        { cityName: "Essex" },
        { cityName: "Surrey" },
        { cityName: "Oxfordshire" },
        { cityName: "Cambridgeshire" },
        { cityName: "Hertfordshire" },
        { cityName: "Dorset" },
        { cityName: "West Midlands" },
        { cityName: "Wiltshire" },
        { cityName: "Cheshire" },
        { cityName: "Warwickshire" },
        { cityName: "Warwickshire" },
        { cityName: "Tyne and Wear" },
        { cityName: "Somerset" },
        { cityName: "Hertfordshire" },
        { cityName: "Somerset" },
        { cityName: "Kent" },
        { cityName: "Northamptonshire" },
        { cityName: "Somerset" },
        { cityName: "Norfolk" },
        { cityName: "Powys" },
        { cityName: "Hertfordshire" },
        { cityName: "Hertfordshire" },
        { cityName: "Shropshire" },
        { cityName: "Middlesex" },
        { cityName: "West Midlands" },
        { cityName: "Surrey" },
        { cityName: "Middlesex" },
        { cityName: "North Yorkshire" },
        { cityName: "Ayrshire" },
        { cityName: "Peeblesshire" },
        { cityName: "Kent" },
        { cityName: "Kent" },
        { cityName: "Wiltshire" },
        { cityName: "Essex" },
        { cityName: "Kent" },
        { cityName: "Avon" },
        { cityName: "West Yorkshire" },
        { cityName: "Surrey" },
        { cityName: "Dorset" },
        { cityName: "Nottinghamshire" },
        { cityName: "North Yorkshire" },
        { cityName: "Shropshire" },
        { cityName: "Cumbria" },
        { cityName: "Dyfed" },
        { cityName: "Tyne and Wear" },
        { cityName: "Kent" },
        { cityName: "Caithness" },
        { cityName: "Essex" },
        { cityName: "Lancashire" },
        { cityName: "Cumbria" },
        { cityName: "Cheshire" },
        { cityName: "Dorset" },
        { cityName: "Somerset" },
        { cityName: "Hampshire" },
        { cityName: "Cumbria" },
        { cityName: "Berkshire" },
        { cityName: "Somerset" },
        { cityName: "Merseyside" },
        { cityName: "Cambridgeshire" },
        { cityName: "Lanarkshire" },
        { cityName: "Essex" },
        { cityName: "Oxfordshire" },
        { cityName: "Surrey" },
        { cityName: "Berkshire" },
        { cityName: "West Midlands" },
        { cityName: "Essex" },
        { cityName: "Hereford and Worcester" },
        { cityName: "Cumbria" },
        { cityName: "Nottinghamshire" },
        { cityName: "Herefordshire" },
        { cityName: "West Sussex" },
        { cityName: "Gloucestershire" },
        { cityName: "Clwyd" },
        { cityName: "Norfolk" },
        { cityName: "Surrey" },
        { cityName: "Devon" },
        { cityName: "Somerset" },
        { cityName: "North Yorkshire" }
    ])
    console.info("Cities are successfully seeded")
}